title: an obsidian PKM generated site autopublishing to github on a jekyll website
author:
  name: sean808080
  email: shh@pobox.com
description: > # this means to ignore newlines until "show_excerpts:"
  love is love

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
#    - { platform: devto,          user_url: "https://dev.to/sean808080" }
 #   - { platform: dribbble,       user_url: "https://dribbble.com/sean808080" }
  #  - { platform: facebook,       user_url: "https://www.facebook.com/sean808080" }
    - { platform: flickr,         user_url: "https://www.flickr.com/photos/sean808080" }
    - { platform: github,         user_url: "https://github.com/jekyll/sean808080" }
 #   - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=sean808080" }
    - { platform: instagram,      user_url: "https://www.instagram.com/sean808080" }
   # - { platform: keybase,        user_url: "https://keybase.io/sean808080" }
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/seanhenriques" }
  #  - { platform: microdotblog,   user_url: "https://micro.blog/sean808080" }
 #   - { platform: pinterest,      user_url: "https://www.pinterest.com/sean808080" }
    - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/931658/sean808080" }
#    - { platform: telegram,       user_url: "https://t.me/sean808080" }
    - { platform: twitter,        user_url: "https://twitter.com/sean808080" }
    - { platform: youtube,        user_url: "https://www.youtube.com/sean808080" }

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag

#remote_theme: material-theme/vsc-material-theme
#remote_theme: squidfunk/mkdocs-material
#remote_theme: pages-themes/architect@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
